
apiVersion: apps/v1
kind: Deployment
metadata:
  name: status-checker

spec:
  replicas: 2
  selector:
    matchLabels:
      app: status-checker
  template: 
    metadata:
      labels:
        app: status-checker
    spec:
      containers: 
      - name: status-checker
        image: status-checker:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080