
apiVersion: v1
kind: Service
metadata:
  name: status-checker-service
spec:
  selector:
    app: status-checker
  ports:
    - protocol : TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer



